name: CI Pipeline
on:
    push:
        branches: [ main ]
    
    pull_request:
        branches: [ main ]

    workflow_dispatch:

jobs:
    event-info-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Trigger event
              run: echo "Trigger event is ${{ github.event_name }}"